baseURL = "//blog.ceshm.com/"
languageCode = "en-us"

title = "Cesar Hernandez"
author = "ceshm"
theme = "contrast-hugo"


[params]
minimal = false
excerpts = false
description = "my blog"


[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "http://www.ceshm.com/"
weight = 10
